// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqRtrzVQSV5hONdkHqG-t2qk8K8k6ZEE',
    appId: '1:693261998763:web:fc47d7be85043a01a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    authDomain: 'flutter-notification-922d1.firebaseapp.com',
    databaseURL: 'https://flutter-notification-922d1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-notification-922d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzFY0-RiUz4N_Fr5oiq9Ws7BCsN23BmI',
    appId: '1:693261998763:android:0c901786841a6474a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    databaseURL: 'https://flutter-notification-922d1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-notification-922d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9B2VI0xq3NrKe2VyFcIdbmYUTwniEQDU',
    appId: '1:693261998763:ios:5dec4e7700591f42a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    databaseURL: 'https://flutter-notification-922d1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-notification-922d1.firebasestorage.app',
    iosBundleId: 'com.example.autoPrinting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9B2VI0xq3NrKe2VyFcIdbmYUTwniEQDU',
    appId: '1:693261998763:ios:5dec4e7700591f42a335ee',
    messagingSenderId: '693261998763',
    projectId: 'flutter-notification-922d1',
    databaseURL: 'https://flutter-notification-922d1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-notification-922d1.firebasestorage.app',
    iosBundleId: 'com.example.autoPrinting',
  );
}
